INSERT INTO PROVINSI (PROVINSI) VALUES ('JAWA TIMUR');

INSERT INTO KOTA (KOTA, PROVINSI_ID) VALUES ('MALANG', 1), ('SURABAYA', 1);

INSERT INTO KECAMATAN (KECAMATAN, KOTA_ID) VALUES ('LOWOKWARU', 1);

INSERT INTO KELURAHAN (KELURAHAN, KECAMATAN_ID, KODE_POS) VALUES ('KETAWANGGEDE', 1, 65145);
